#:import MapView kivy.garden.mapview.MapView
#:import GpsBlinker gpsblinker.GpsBlinker
#:include gpsblinker.kv
#:include teammarker.kv

<TeamMapView>:
    zoom: 16
    lon: self.markers[0][0]
    lat: self.markers[0][1]
    on_zoom:
        self.zoom = 13 if self.zoom < 13 else self.zoom
    on_lat:
        self.draw_markers()
    on_lon:
        self.draw_markers()
    GpsBlinker:
        id: blinker
        #lon: root.longitude
        #lat: root.latitude